function calculateArea(width,height){
	var area = width * height;//MAKES A VARIABLE THAT SAVES AS THE VALUE OF WIDTH AND HEIGHT
  return area;
//THIS IS A FUNCTION THAT THAT TAKES 2 PARAMETERS.
}
var a = prompt("SUP DUMMY GIVE ME A WIDTH PLS");//ASKS USER FOR WIDTH, SAVES AS VALUE a
var b = prompt("K DUMMY GOOD JOB NOW GIVE ME A LENGTH");//ASKS USER FOR LENGTH, SAVES AS VALUE b
var x = calculateArea(a,b);//MULTIPLIES a AND b AND SAVES IT AS VARIABLE x
window.alert(x);//WINDOW ALERTS X WHICH WILL SHOW THE VALUE OF a AND b THAT WAS MULTIPLIED